
-- RESPOSTA 1 - UPDATE NOS REGISTROS:
UPDATE CLIENTE SET NUMERO=985 WHERE NOME='PRISCILA';
UPDATE CLIENTE SET NUMERO=1950,COMPLEMENTO='Bloco H-Ap. 4' WHERE NOME='Karina';
UPDATE CLIENTE SET NUMERO=23, COMPLEMENTO='Casa Fundos' WHERE NOME='Cibele';
UPDATE CLIENTE SET NUMERO=950 WHERE NOME='Marcela';
UPDATE CLIENTE SET NUMERO=26 WHERE NOME='Roberto';

-- RESPOSTA 2 - 'PROCEDURE' PARA ATUALIZAR O CAMPO 'VALOR_TOTAL' DA TABELA 'PEDIDO'
DELIMITER $$
CREATE PROCEDURE PRC_ATUALIZA_VALOR_PEDIDO(IN pID INT, IN pQTD INT, IN pVAL DECIMAL(10,2))
BEGIN
	DECLARE VALORITEM DECIMAL(10,2);
	SET VALORITEM = pVAL * pQTD;
	UPDATE PEDIDO SET VALOR_TOTAL = VALOR_TOTAL + VALORITEM WHERE ID = pID;
END $$
DELIMITER ;


-- RESPOSTA 3 - TRIGGER PARA ACIONAR A 'PROCEDURE' DA QUESTÃO 2
DELIMITER ||
CREATE TRIGGER TRG_ACIONA_PRC_ATUALIZA_VALOR_PEDIDO
AFTER INSERT ON ITEM_PEDIDO
FOR EACH ROW
BEGIN	
	CALL PRC_ATUALIZA_VALOR_PEDIDO(NEW.PEDIDO_ID, NEW.QUANTIDADE, NEW.VALOR_ITEM);
END|| 
DELIMITER ;

-- RESPOSTA 4 
-- UTILIZADO FUNÇÃO 'DATE_ADD', UTILIZADA PARA ADICIONAR UM INTERVALO DE TEMPO A UMA DATA, ABAIXO TEMOS UM 'UTPDATE' SIMPLES SEGUIDO DE UM EXEMPLO ONDE OCORRE A VALIDAÇÃO 'DATA_HORA_INI' ANTES DA ALTERAÇÃO
UPDATE pedido SET data_hora_fim = DATE_ADD(data_hora_ini, INTERVAL 1 HOUR);

-- COM VERIFICAÇÃO DE 'DATA_HORA_INI' NÃO É NULO
UPDATE pedido
SET data_hora_fim = DATE_ADD(data_hora_ini, INTERVAL 1 HOUR)
WHERE data_hora_ini IS NOT NULL;

-- RESPOSTA 5
-- SELECIONAR OS 20 PEDIDOS DE MAIOR VALOR ORDENADOS POR ORDEM DECRESCENTE;

SELECT * 
FROM PEDIDO
ORDER BY VALOR_TOTAL DESC
LIMIT 20;

-- RESPOSTA 6
-- SELECIONAR OS 20 PEDIDOS DE MENOR VALOR ORDENADOS POR ORDEM CRESCENTE;

SELECT * 
FROM PEDIDO
ORDER BY VALOR_TOTAL 
LIMIT 20;

-- RESPOSTA 7
-- SELECIONAR OS CLIENTES DAS QUESTÕES 5 E 6 EXIBINDO O NOME, CPF E UM TELEFONE (CASO EXISTA);

-- REF 5
SELECT DISTINCT
    CLI.NOME AS 'NOME CLIENTE',
    (SELECT TEL.NUMERO 
     FROM TELEFONE TEL 
     WHERE TEL.CLIENTE_ID = CLI.ID 
     LIMIT 1) AS TELEFONE,
    CLI.CPF,
    PED.ID,
    ENT.NOME,
    PED.DATA_HORA_INI,
    PED.DATA_HORA_FIM,
    PED.VALOR_TOTAL AS VALOR_TOTAL
FROM
    PEDIDO AS PED
        INNER JOIN
    CLIENTE CLI ON PED.CLIENTE_ID = CLI.ID
        INNER JOIN
    ENTREGADOR AS ENT ON ENT.ID = PED.ENTREGADOR_ID    
ORDER BY VALOR_TOTAL DESC
LIMIT 20;

-- REF 6
SELECT DISTINCT
    CLI.NOME AS 'NOME CLIENTE',
    (SELECT TEL.NUMERO 
     FROM TELEFONE TEL 
     WHERE TEL.CLIENTE_ID = CLI.ID 
     LIMIT 1) AS TELEFONE,
    CLI.CPF,
    PED.ID,
    ENT.NOME,
    PED.DATA_HORA_INI,
    PED.DATA_HORA_FIM,
    PED.VALOR_TOTAL AS VALOR_TOTAL
FROM
    PEDIDO AS PED
        INNER JOIN
    CLIENTE CLI ON PED.CLIENTE_ID = CLI.ID
        INNER JOIN
    ENTREGADOR AS ENT ON ENT.ID = PED.ENTREGADOR_ID    
ORDER BY VALOR_TOTAL 
LIMIT 20;

-- RESPOSTA 8
-- CRIAR UM SELECT QUE EXIBA OS SEGUINTES CAMPOS:
-- **NOME**, **TELEFONE** E **CPF** (TABELA *CLIENTE*)
-- **ID** DO PEDIDO, **DATA/HORA** DA FINALIZAÇÃO E **VALOR_TOTAL** (TABELA *PEDIDO*) 
-- **NOME** DO ENTREGADOR (TABELA *ENTREGADOR*)

SELECT 
    PED.ID 'ID PEDIDO',
    CLI.NOME AS 'NOME CLIENTE',
    (SELECT 
            TEL.NUMERO
        FROM
            TELEFONE TEL
        WHERE
            TEL.CLIENTE_ID = CLI.ID
        LIMIT 1) AS TELEFONE,
    CLI.CPF,
    ENT.NOME,
    PED.DATA_HORA_FIM,
    PED.VALOR_TOTAL AS VALOR_TOTAL
FROM
    PEDIDO AS PED
        INNER JOIN
    CLIENTE CLI ON PED.CLIENTE_ID = CLI.ID
        INNER JOIN
    ENTREGADOR AS ENT ON ENT.ID = PED.ENTREGADOR_ID
ORDER BY PED.ID;






